name: deploy-preview

on:
  pull_request:

jobs:
  deploy-preview:
    if:
      "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount:
            "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANJODATO_ADD8B }}"
          projectId: anjodato-add8b
